### ISSUE TITLE
Additional patterns in the real world

### ISSUE THREAD

**Issue by mbordogna** [snd/url-pattern#23]
Overall great job so far but there are a few real world examples that you should consider for tests.

I realize you are in v.1, but the examples I have provided would need to be solved to really get this library into a production systems and through a real system release process. .e.g. dev, qa, staging, prod.

Below are common real world examples that should probably have unit tests
domain tests
https://localhost:9098/resource/
https://domain.com:8879/resource/id
parameter tests
/api/users/somesuer@example.com - doesn't work 
nor /api/users?username=someone@example.com (best i can get is /api/users?somename
/api/users?param1=test&param2=next

I was unable to add @ or = to the valid char sets so that restricted this as well.
I real world rest implementations it is common practice to not create parameters to support actions,

Couple things to keep in mind.
1. Action Parametesrs -  POST /api/myresource?validate=true
2. Email is a pretty common value to be in uri
3. Search/query parameters are pretty common in uri 
4. DEV and even QA environments almost always user port numbers. 
5. identify the host may be good enough, its easy to spit on dots and : if needed domain segments
6. "." is an allowable value in an email address, mine has one.

sample i have been playing with below

var options = {};
options.segmentNameCharset = '\@\.a-zA-Z0-9_-';
var pattern = new UrlPattern('(*)/api(/ref)/:resource(/:id)(/:child)(/:subId)(?*:params)', options);
var result = pattern.match("https://sss.www.localhost.com//api/security/bob@example");
console.log(result);

**Comment by snd** [comment]
hey,

> I realize you are in v.1, but the examples I have provided would need to be solved to really get this library into a production systems and through a real system release process. .e.g. dev, qa, staging, prod.

**all the examples you’ve provided are perfectly possible with url-pattern !**

read on below for details.

url-pattern is very much used in production in the real world !

as far as i'm aware url-pattern is mostly used (in other libraries) to deal with the path part of an URL.

i general i can help you more quickly if you state precisely what you are trying to do, the code you've written, what you expect the code to do, what the code does instead (wrong output, error message, etc)
without making too many assumptions.

thanks for providing additional test fixtures.

regarding query strings please read this:
https://github.com/snd/url-pattern#how-do-i-match-the-query-part-of-an-url-

> domain tests
> https://localhost:9098/resource/
> https://domain.com:8879/resource/id

[see this](https://github.com/snd/url-pattern/blob/c8e0a943bb62e6feeca2d2595da4e22782e617ed/test/match-fixtures.coffee#L181)
[and this](https://github.com/snd/url-pattern/blob/c8e0a943bb62e6feeca2d2595da4e22782e617ed/test/match-fixtures.coffee#L195)

> /api/users/somesuer@example.com - doesn't work 

[yes it does](https://github.com/snd/url-pattern/blob/c8e0a943bb62e6feeca2d2595da4e22782e617ed/test/match-fixtures.coffee#L166)

keep in mind that `@` is reserved in URLs for the auth part. so you should probably escape it when using it in the path part or query part.

> nor /api/users?username=someone@example.com (best i can get is /api/users?somename
/api/users?param1=test&param2=next

[see this](https://github.com/snd/url-pattern/blob/c8e0a943bb62e6feeca2d2595da4e22782e617ed/test/match-fixtures.coffee#L171)

> I was unable to add @ or = to the valid char sets so that restricted this as well.

[see this](https://github.com/snd/url-pattern/blob/c8e0a943bb62e6feeca2d2595da4e22782e617ed/test/match-fixtures.coffee#L171)

> 1. Action Parametesrs - POST /api/myresource?validate=true

i don't quite understand what you mean.

> 3. Search/query parameters are pretty common in uri 

regarding query strings please read this:
https://github.com/snd/url-pattern#how-do-i-match-the-query-part-of-an-url-

> 4. DEV and even QA environments almost always user port numbers. 

[you can easily match ports with url-pattern](https://github.com/snd/url-pattern/blob/c8e0a943bb62e6feeca2d2595da4e22782e617ed/test/match-fixtures.coffee#L195)

> 6. "." is an allowable value in an email address, mine has one.

i'd say pretty much every email has one.
[it's easy to make url-pattern consume the dot when reading a named segment: just add it to `segmentValueCharset`](https://github.com/snd/url-pattern/blob/c8e0a943bb62e6feeca2d2595da4e22782e617ed/test/match-fixtures.coffee#L167)

> var options = {};
> options.segmentNameCharset = '\@.a-zA-Z0-9_-';
> var pattern = new UrlPattern('()/api(/ref)/:resource(/:id)(/:child)(/:subId)(?:params)', options);
> var result = pattern.match("https://sss.www.localhost.com//api/security/bob@example");
> console.log(result);

this throws at  `new UrlPattern('()/api(/ref)/:resource(/:id)(/:child)(/:subId)(?:params)', options);` with `couldn’t parse pattern` because the pattern you’ve written is not a valid url-pattern.
[see this for a working similar example](https://github.com/snd/url-pattern/blob/c8e0a943bb62e6feeca2d2595da4e22782e617ed/test/match-fixtures.coffee#L211).
you probably meant `segmentValueCharset` instead of `segmentNameCharset`.
there's no need to escape `@` in the charset.

hope this helps.
