### ISSUE TITLE
Stringify URL with arbitrary-length lists

### ISSUE THREAD

**Issue by skatenerd** [snd/url-pattern#27]
Looking at [the tests](https://github.com/snd/url-pattern/blob/master/test/stringify-fixtures.coffee), I'm not sure if I can craft a `UrlPattern` that behaves in the following way:

`(new UrlPattern(myUrl)).stringify({a: [1,2,3]})` -> `www.yahoo.com?p=1&p=2&p=3`
`(new UrlPattern(myUrl)).stringify({a: [1,2,3,4,5,6]})` -> `www.yahoo.com?p=1&p=2&p=3&p=4&p=5&p=6`

I could leverage [optional params](https://github.com/snd/url-pattern/blob/master/test/stringify-fixtures.coffee#L88) to give myself the option of adding up-to-N-parameters:
`myUrl = www.yahoo.com?(p=:a(&p=:a(&p=:a(&p=:a))))`

But this seems kind of inelegant.

How do you think the API would ideally look for this?

**Comment by snd** [comment]
you can't currently create an url-pattern that behaves those ways.

dealing with the query part of an url is intentionally outside the scope of url-pattern as that part has different semantics and there are other libraries far better suited to dealing with it.
see this FAQ entry https://github.com/snd/url-pattern#how-do-i-match-the-query-part-of-an-url-

the stringifying part of url-pattern is the easy part.
the parsing part is much more involved (that's why i originally created url-pattern).

**in this case it is very easy to build the desired functionality yourself**:

```js
> 'www.yahoo.com?' + [1, 2, 3].map(item => 'p=' + item).join('&')
'www.yahoo.com?p=1&p=2&p=3'
```

you get the idea...

hope this helps

**Comment by skatenerd** [comment]
Thanks.  I actually went with the optional-params, just to make the code consistent with other invocations of the library :-)
