### ISSUE TITLE
Provided typings do not work for TS2

### ISSUE THREAD

**Issue by ghost** [snd/url-pattern#35]
On TS 2.0.10, attempting to use UrlPattern like this:

`import { UrlPattern } from 'url-pattern';`

This fails with error:
.........node_modules/url-pattern/index"' has no exported member 'UrlPattern'.

Do you only support a particular TS version?

**Comment by snd** [comment]
@mikaelwaltersson added the typescript typings initially. i have little experience with typescript.

@mikaelwaltersson or @dawnofthedev  are you interested in adding support for TS 2.0.10? that would be great!

**Comment by mikaelwaltersson** [comment]
Hi, sorry for the delayed response. 

In this case there is nothing wrong with the typings, can't vouch for really early versions of TypeScript but there should be no problem using it from 2.0.0 and later.

The problem here is that url-pattern doesn't export a member named UrlPattern, instead it export a single unnamed object.

Use the following line to import the library instead:

`import * as UrlPattern from 'url-pattern';`

This issue should be closed

**Comment by ghost** [comment]
Thanks it works. You should include that in the docs.
