### ISSUE TITLE
Unlimited subdomains?

### ISSUE THREAD

**Issue by vaiulian** [snd/url-pattern#36]
Hi,

i can't see to find how i can achieve matching an unlimited number of sub domains.

i did something like 
`new UrlPattern("((:protocol)\\://)((((((:subdomain.):subdomain.):subdomain.):subdomain.):subdomain.):domain.)(:tld)(\\:(:port))(/*)")`

hoping there would not be more than 5 but it appears that my application encounters links with more than 5. I could write for 6 or 7 or 8 but that wouldn't do me much good.

I was looking for a `([:subdomain\.]?)` regex syntax like format. 

Thanks

**Comment by knoxcard** [comment]
/https?:\/\/(\S*\.)?yourdomain\.net/

https://stackoverflow.com/questions/38484378/javascript-regex-match-domain-and-any-possible-sub-domain

**Comment by knoxcard** [comment]
/http[s]?://(\S*.)?yourdomain.net/

[s] to handle both http and https

**Comment by snd** [comment]
url-pattern does not have a way to do regex like repetition at the moment.
i might implement that in the future if a sensible proposal comes along.

you could try using a wildcard `*` instead of the subdomains part, then matching and splitting the result by `.` to get the individual subdomains

url-patterns only goal is to make expressing certain very common string patterns easier than it would be using regexes.
it is not intended as a replacement to regexes. more like an additional tool. sometimes regexes are the better choice

**Comment by vaiulian** [comment]
@snd Yeah, i figured that out eventually.

I did a regex based URL Pattern like `^([a-zA-Z]+:\/\/)?(([\w]*)(\.{1}[\w]+)+)(:[0-9]+)?(\/.+)?` this gave me the tld and domain, and the remaining part of the `(([\w]*)(\.{1}[\w]+)+)` if any, was the subdomain(s) that i split by `.`

You can close this, i guess.

Thanks
