### ISSUE TITLE
How to match encoded URI?

### ISSUE THREAD

**Issue by AlexZeitler** [snd/url-pattern#41]
I have this Pattern:

```js
const template = '/members/:userId'
const pattern = new UrlPattern(template);
const match = pattern.match(url);
```

if my `url` looks like this `/members/user%40example.org` I don't get a match.

**Comment by AlexZeitler** [comment]
This works:

```js
const template = '/members/(*)'
```
But it feels like a brute force approach. :grimacing:

**Comment by snd** [comment]
hey alex,

it's better to first decode the string and then match

```javascript
const match = pattern.match(decodeURIComponent(url))
```

this doesn't fully solve your problem however.

the problem is that the decoded string contains characters `.` and `@` which url-pattern doesn't match as part of a named segment.
full explanation is here: https://github.com/snd/url-pattern#named-segments.
after adding those chars to the `segmentValueCharset` it matches correctly.
people have in the past wanted very different things from url-pattern ("match this but don't match this", etc).
that's why i added sensible defaults for simple cases but made it customizable.

complete working solution:

```javascript
const template = '/members/:userId'
const options = {
  segmentValueCharset: "a-zA-Z0-9-_~ %@."
}
const pattern = new UrlPattern(template, options)
const url = "/members/user%40example.org"
const decodedUrl = decodeURIComponent(url)
console.log(decodedUrl)
const match = pattern.match(decodeURIComponent(url))
console.log(match)
```

**Comment by AlexZeitler** [comment]
@snd Thanks, your sample works as expected!

**Comment by ktosiek** [comment]
Just for the record: *please* don't decode before matching. This will let user-provided values "escape" from their place: `"/user/fancyUser123%2Fpages/profile"` should match a pattern like `/user/:username/profile`, but if you decode the path it will instead match `/user/:username/pages/profile` - the encoded "/" will become part of the path, instead of being a part of a path component.

Decoding should only be done after splitting the path into components.
